// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfhybzemirlpcynhjosk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmaHliemVtaXJscGN5bmhqb3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDkxMjUsImV4cCI6MjA1ODEyNTEyNX0.iQpPteRheZR6BTCliqg9QJODNy14YvQs3KRODt7OeL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);